title: Blog of Janibek
email: zhanibekmarshal+website@gmail.com
description: >-
  Android developer from land of steppe.
  Working at Zattoo as Android team lead.
# Url configuration
baseurl: ""
url: "http://marshal.kz"
# Social networks
twitter_username: megasuperhero
github_username:  JohnMars
instagram_username: john_marshal
# Commenting
disqus:
  shortname: janibek-marshal

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

google_analytics: UA-110082079-2

collections:
  - portfolios

sass:
  sass_dir: _scss
  style: :compressed
